##七牛云的key
qiniu:
  accessKey: 0j0DJNycJ8YTqLlgh22aKM57vfeAnfsuQy8ZrBDP
  secretKey: _mj_dSZo93IGCjZ3JpusTNGWDMjfslfgZFWhnNSw
  bucketName: tencent
  basePath: https://qiniu.ouyanglol.com/

## 百度推送
baidu:
  task:
    postUrl: http://data.zz.baidu.com/urls?site=blog.ouyanglol.com&token=Wz31n3ETMHzfyFkg
    baseUrl: https://blog.ouyanglol.com

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://119.29.169.96:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: fourge55
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: ouyang-blog

#mynatis配置
mybatis:
  type-aliases-package: com.ouyang.zblog.vo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml
#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file:
server:
  session-timeout : 3600
  port: 8085



